### ISSUE TITLE
unable to install modules

### ISSUE THREAD

**Issue by Suman121** [libindic/Silpa-Flask#36]
I am trying to get this work at my system. I followed installation instruction given in Silpa documents (http://silpa.readthedocs.io/en/latest/installation.html). 
But when i tried to install modules. But getting error in installing ngram module. There is an issue raised regarding it on this link (https://github.com/libindic/Silpa-Flask/pull/31). I am not sure whether it is fix or not. Can anyone please look into it. I am also attaching screen shot for your refernce.
![ngrammodulefailed](https://cloud.githubusercontent.com/assets/19682851/24185031/ff869ab4-0ef6-11e7-8c7c-707e4cbb34fb.png)

Thanks in advance for help.

**Comment by copyninja** [comment]
@balasankarc I think ngram issue I already mentioned earlier is what he is facing. Where you able to fix this?
